name: chatacter
description: "A new Flutter project."
version: 1.0.0+1
environment:
    sdk: ">=3.3.4 <4.0.0"
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.6
    http: ^1.2.1
    animated_text_kit: ^4.2.2
    font_awesome_flutter: ^10.7.0
    url_launcher: ^6.2.5
    google_fonts: ^6.2.0
    path_provider: ^2.0.8
    get: ^4.6.6
    flutter_launcher_icons: ^0.13.1
    url_launcher_windows: ^3.1.1
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    build_runner: ^2.4.9
    custom_lint: ^0.6.4
flutter:
    uses-material-design: true
    assets:
        - assets/
flutter_launcher_icons:
    android: true
    image_path: "assets/logo.png"
    web:
        generate: true
        image_path: "assets/logo.png"
    windows:
        generate: true
        image_path: "assets/logo.png"
        icon_size: 48 # min:48, max:256, default: 48
